### ISSUE TITLE
Target {{word}} can't be its alternative writing

### ISSUE THREAD

**Issue by Ceynou** [Ben-Kerman/immersive#12]
For exemple, the word 玉 has these alternative writings in the dictionary entry:
球 【たま】、珠 【たま】、弾 【たま】

So even if you select one of those alternative, the {{word}} output will always end up being the base writing.
![anki_1BadZk2Rog](https://user-images.githubusercontent.com/41862916/121797145-b86a6e00-cc1e-11eb-9990-ff98d07ac5e7.png)

**Comment by Ben-Kerman** [comment]
This would be a relatively complicated feature to implement, doesn't happen that often in my experience, and is really easy to fix manually when it does happen, so I'll close the issue for now

That being said, I just added a new template variable that contains the original selection, so you can somewhat solve it by using `{{selections}}` instead of `{{word}}` with the newest commit (but that doesn't work well with deinflection, so pick your poison)

Maybe I'll add a nice solution in the future, but no idea when, if at all
