### ISSUE TITLE
Ability to export Target word without selecting a definition (Suggestion)

### ISSUE THREAD

**Issue by Ceynou** [Ben-Kerman/immersive#15]
When your dictionary doesn't have an entry for the word you're selecting or even its short form, the current solution is to select a random word with a definition and fix that later on anki, an option to allow this would be nice.

**Comment by Ben-Kerman** [comment]
You can export without any target words and add a definition manually (afaik even if the word goes into your sort field, it'll put a placeholder there in that case). If it's just a matter of that particular form of a word not being in the dictionary you can copy it from somewhere else and look up from clipboard in the target select menu with `v`, or use a [deinflector](https://github.com/Ben-Kerman/immersive/blob/master/doc/lookup-transformations.md) will help).

If that solves the issue close it, otherwise I'll use this issue as a reminder to look into how to implement this when I get some time to add some larger features

**Comment by Ceynou** [comment]
Well I don't know what I missed or messed with but it definitely does work perfectly fine, thank you
