### ISSUE TITLE
Immersive "disappears"/freezes when trying to play Forvo audio.

### ISSUE THREAD

**Issue by sbstratos79** [Ben-Kerman/immersive#8]
mpv version : mpvnet 0.32.0-410-g640db1ed3f

Immersive is behaving strangely for me.
If I try to listen to the forvo audio, the Immersive ui disappears and it stops responding to hotkeys. I have to restart mpv to get it to work again.
Immersive throws an error when mpv is loading "invalid boolean ('<...>'), must be 'yes', 'true', 'no' or 'false' "
Sometimes when selecting the target word it shows the error "digit replacement has the wrong length <...>"
If I export the cards to Anki, the image and audio is broken. I can open another issue for that if you want.

I have attached the log file for the forvo audio error. 
[log.txt](https://github.com/Ben-Kerman/immersive/files/6343720/log.txt)

**Comment by Ben-Kerman** [comment]
> If I try to listen to the forvo audio, the Immersive ui disappears and it stops responding to hotkeys.

> If I export the cards to Anki, the image and audio is broken.

Looks like the script can't start new instances of mpv for playing Forvo clips/audio preview and encoding audio and images. Until now the script crashed if the mpv instance for background playback was missing, but I added a check so in future versions it should show an error instead.

I'm not sure why that happens, but if I had to guess it probably has something to do with you using mpv.net instead of regular mpv. I'm not sure how to fix it (other than switching to normal mpv), but try replacing the script with the version from [this archive](https://github.com/Ben-Kerman/immersive/files/6344167/immersive-85b6df2-1-script.zip). If that works let me know. If it doesn't, extract the latest build from [here](https://sourceforge.net/projects/mpv-player-windows/files/) somewhere and put the folder that contains `mpv.exe` and `mpv.com` in your PATH. If that works I'll add a note to the installation instructions.

> Immersive throws an error when mpv is loading "invalid boolean ('<...>'), must be 'yes', 'true', 'no' or 'false' "
> Sometimes when selecting the target word it shows the error "digit replacement has the wrong length <...>"

Because you uncommented `preload` and `export:digits` in the dictionary config without setting them to a valid value. `preload` must be one of those words (`yes`/`true`/`no`/`false`) and `export:digits` has to be exactly 10 characters long (and mostly exists to replace halfwidth with fullwidth digits, so you probably don't need it anyway). If you're just using JMdict this is all you need in the dict config file as long as you're ok with the default templates:
```
[JMdict]
location=...
type=yomichan
```

**Comment by sbstratos79** [comment]
Thanks. I fixed the config file.
I tried the immersive zip you provided. Now it doesn't crash but throws an error instead "could not connect to background player". So that's good.
I uninstalled mpvnet and installed vanilla mpv but that isn't working either. Same error.

**Comment by Ben-Kerman** [comment]
I changed the name of the exe it tries to run to `mpvnet` in the archive from before.

Try [this version](https://github.com/Ben-Kerman/immersive/files/6344797/immersive-85b6df2-2-script.zip) instead. It's the same but with the regular exe filename instead.

**Comment by sbstratos79** [comment]
This one works.  Thanks!
